<html>
<head>
<title>Test Zend 2</title>
<?php echo $this->headLink()->appendStylesheet('/css/style.css') ?>
<?php echo $this->headScript()->appendFile('/js/jquery-1.6.min.js','text/javascript'); ?>
<script>
$(document).ready(function(){
   $("#logoname a").hover(function(){
       $("#tagline").animate({'font-size':'150px'}, 370);
   },function(){
       $("#tagline").animate({'font-size':'8px'});
   }) 
});

</script>
</head>
<body>
<div id="header">

<div id="headerleft">
    <div id="logo"></div>
    <div id="logoname"><a href="<?php echo $this->url(array('controller'=>'index')) ?>">SquareSite<sup>&reg;</sup></a><div id="tagline">Designing is Gay</div></div>
    <div class="c"></div>
</div>

<div id="headerright">
<ul>
    <li><a href="<?php echo $this->url(array('controller'=>'about','action'=>'')) ?>">About</a></li>
    <li><a href="<?php echo $this->url(array('controller'=>'contact','action'=>'')) ?>">Contact</a></li>
</ul>
</div>


</div>

<div id="maincenter"><?php echo $this->layout()->content; ?></div>
<div id="footer">&copy; SquareSite <?php echo date('Y'); ?>. All rights reserved</div>
</body>
</html>